# resnet 32 for benchmarking incremental method on cifar 100

network:
  name: resnet32
  num_classes: '@{dataset.num_classes}' # this should reflect # class in total, # class for each il learning is
  pretrained: False # In training pipeline:"False"; In testing pipeline:"True"
  num_gpus: '@{num_gpus}'
  checkpoint: none
  backbone:
    name: resnet32
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: False
    checkpoint: none
    num_gpus: '@{num_gpus}'
