exp_name: "'@{trainer.name}'_'@{dataset.name}'_'@{network.name}'_increment_pt'@{increment}'"
output_dir: ./results/results_cil_only/
save_output: True
merge_option: default
mark: default

num_gpus: 1
num_workers: 4
num_machines: 1
machine_rank: 0

num_tasks: None
increment: 10 # use interchangeably with num task (10 class per task)
fixed_memory: false

device: 'cuda:0'
# device: ["cuda:0","cuda:1","cuda:2","cuda:3"]
seed: 1993


preprocessor:
  name: base

network:
  pretrained: False

pipeline:
  name: cil_only

trainer:
  name: incremental_wa

optimizer:
  init_epoch: 200 #200
  init_lr: 0.1
  init_milestones: [60, 120, 170]
  init_lr_decay: 0.1
  init_weight_decay: 0.0005

  epochs: 170 # 170
  lrate: 0.1
  milestones: [60, 100, 140]
  lrate_decay: 0.1
  weight_decay: 0.0002
  num_workers: 8
  T: 2

recorder:
  name: base
  save_all_models: False
  save_scores: True
  save_csv: False
