ood_dataset:
  name: imagenet_ood
  num_classes: 1000

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  
  dataset_class: FragmentedOODDataset
  interpolation: bilinear
  batch_size: 32
  shuffle: False

  pre_size: 256
  image_size: 224

  split_names: [val, nearood, farood]
  val:
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet/val_openimage_o.txt
    dataset_class: ImglistDataset
  nearood:
    datasets: [species, inaturalist, openimageo, imageneto]
    inaturalist:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_inaturalist.txt
    openimageo:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_openimage_o.txt
    imageneto:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_imagenet_o.txt
    species:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_species.txt
  farood:
    datasets: [texture, mnist]
    texture:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_texture.txt
    mnist:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_mnist.txt
