dataset:
  name: imagenet_cil
  num_classes: 1000
  image_size: 224
  pre_size: 256

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  # for exemplar sets
  memory_size: 20000
  memory_per_class: 20
  increment: 10

  # shuffle order
  shuffle_order: true

  # setting: train from half or train from scratch
  init_cls_tfs_thf: 0


  split_names: [train, val, test]

  train:
    dataset_class: IncrementalDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet/train_imagenet.txt
    batch_size: 128
    shuffle: True
  val:
    dataset_class: IncrementalDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet/val_imagenet.txt
    batch_size: 128
    shuffle: False
  test:
    dataset_class: IncrementalDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet/test_imagenet.txt
    batch_size: 128
    shuffle: False
