dataset:
  name: cifar100_cil
  num_classes: 100
  image_size: 32
  pre_size: 32

  interpolation: bilinear
  normalization_type: cifar100

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  # for exemplar sets
  memory_size: 2000
  memory_per_class: 20
  increment: 10

  # shuffle order
  shuffle_order: true

  # setting: train from half or train from scratch
  init_cls_tfs_thf: 0


  split_names: [train, val, test]

  train:
    dataset_class: IncrementalDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/train_cifar100.txt
    batch_size: 128
    shuffle: True
  val:
    dataset_class: IncrementalDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/val_cifar100.txt
    batch_size: 128
    shuffle: False
  test:
    dataset_class: IncrementalDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/test_cifar100.txt
    batch_size: 128
    shuffle: False
