exp_name: "'@{trainer.name}'_'@{postprocessor.name}'_'@{dataset.name}'_'@{network.name}'_increment_pt'@{increment}'"
output_dir: ./results/results_ood_after_cil/
ckpt_path: ./results/results_cil_only/'@{trainer.name}'_'@{dataset.name}'_'@{network.name}'_increment_pt'@{increment}'

save_output: True
merge_option: default
mark: default

num_gpus: 1
num_workers: 4
num_machines: 1
machine_rank: 0
fixed_memory: false


num_tasks: None
increment: 10 # use interchangeably with num task (10 class per task)

device: 'cuda:0'
seed: 1993


preprocessor:
  name: base

network:
  pretrained: False

pipeline:
  name: ood_after_cil

trainer:
  name: incremental_wa

evaluator:
  name: ood_cil

optimizer:
  init_epoch: 200
  init_lr: 0.1
  init_milestones: [60, 120, 170]
  init_lr_decay: 0.1
  init_weight_decay: 0.0005

  epochs: 170
  lrate: 0.1
  milestones: [60, 100, 140]
  lrate_decay: 0.1
  batch_size: 128
  weight_decay: 0.0002
  num_workers: 8
  T: 2

recorder:
  name: base
  save_all_models: False
  save_scores: True
  save_csv: False
